name: "📎 Pull Request Labeler"

# The workflow will run on pull requests.
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on:
      - ubuntu-latest

    steps:
      - uses: actions/labeler@v6 # https://github.com/actions/labeler
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml